USE MASTER
GO
DROP DATABASE ENCASA
GO  
USE MASTER
GO
CREATE DATABASE ENCASA
GO
--CREACION DE TABLAS--
USE ENCASA
GO 
CREATE TABLE ARTICULOS(
    ID INT NOT NULL IDENTITY(1,1),
    CODIGO VARCHAR(25) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(150) NULL,
    IDCATEGORIA INT NOT NULL,
    IDMARCA INT NOT NULL,
    IDPROVEEDOR INT NOT NULL,
    PRECIO MONEY NOT NULL,
    CANTIDAD INT NULL,
    EXISTENCIA INT DEFAULT 1, 
    IDORIGEN INT NULL,
    IMAGEN VARCHAR (200) NULL 
)
GO
CREATE TABLE CATEGORIAS(
    ID INT NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL
)
GO
CREATE TABLE MARCAS(
    ID INT NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR(75) NOT NULL
)
GO
CREATE TABLE PROVEEDORES(
    ID INT NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR(75) NOT NULL,
    DESCRIPCION VARCHAR(150) NULL,
    DIRECCION VARCHAR (150) NOT NULL
)
GO
CREATE TABLE PAISES(
    ID INT NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR (50) NOT NULL
)

-- CREACION DE PRIMARY KEY--
ALTER TABLE ARTICULOS
ADD CONSTRAINT PK_ARTICULOS PRIMARY KEY (ID)
GO
ALTER TABLE CATEGORIAS
ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID)
GO
ALTER TABLE MARCAS
ADD CONSTRAINT PK_MARCA PRIMARY KEY (ID)
GO
ALTER TABLE PROVEEDORES 
ADD CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID)
GO 
ALTER TABLE PAISES
ADD CONSTRAINT PK_PAIS PRIMARY KEY (ID)

--CREACION DE FOREIGN KEY--
GO
ALTER TABLE ARTICULOS
ADD CONSTRAINT FK_CATEGORIAS FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIAS(ID)
GO
ALTER TABLE ARTICULOS
ADD CONSTRAINT FK_MARCAS FOREIGN KEY(IDMARCA) REFERENCES MARCAS(ID)
GO
ALTER TABLE ARTICULOS
ADD CONSTRAINT FK_PROVEEDORES FOREIGN KEY(IDPROVEEDOR) REFERENCES PROVEEDORES(ID)
GO
ALTER TABLE ARTICULOS
ADD CONSTRAINT FK_ORIGEN FOREIGN KEY(IDORIGEN) REFERENCES PAISES(ID)

-- SELECT a.ID, A.CODIGO, a.NOMBRE, a.DESCRIPCION, a.EXISTENCIA, a.IMAGEN, a.PRECIO, a.CANTIDAD, m.NOMBRE as nombreMarca, m.ID as idMarca, c.NOMBRE as nombreDesc, c.ID as idCat, p.NOMBRE as paisOrig, p.ID as idOrig FROM Articulos as A INNER JOIN MARCAS as M on m.ID = a.IDMARCA INNER JOIN Categorias as C on C.ID = a.IDCATEGORIA INNER JOIN PAISES AS P ON P.ID = A.IDORIGEN

insert into MARCAS values ('Arredo'), ('Arcoiris'), ('Livanlito'), ('Delta'), ('Sama')
insert into CATEGORIAS values ('Blanqueria'),('Muebles'), ('Lamparas'), ('Alfombras'), ('Orden')
insert into PROVEEDORES VALUES ('Pepe', 'Alto proveedor', 'su casa')
insert into PROVEEDORES VALUES ('Pepito', 'Alto proveedor', 'su casa')
insert into PROVEEDORES VALUES ('Pepecito', 'Alto proveedor', 'su casa')
INSERT INTO PAISES VALUES('Argentina')
insert into ARTICULOS values ('S001', 'Sabanas Animal Print', 'Tela de 180 hilos', 1, 2, 1, 2750, 1, 1,1,'https://http2.mlstatic.com/juego-sabanas-2-12-plazas-animal-print-euro-percal-oregon-D_NQ_NP_774916-MLA27680795517_072018-F.jpg')
insert into ARTICULOS values ('MPH007', 'Estante flotante', 'Madera lacada', 2, 3, 2, 60050, 1, 1,1,'https://http2.mlstatic.com/estantes-repisas-flotantes-todas-las-medidas-lemensiedeco-D_NQ_NP_662276-MLA31016626802_062019-F.jpg')
insert into ARTICULOS values ('APB003', 'Alfombra para Baño', 'Absorbe el agua', 4, 4, 2, 1050, 1, 1,1,'https://d26lpennugtm8s.cloudfront.net/stores/501/942/products/633415-mla25233543771_122016-o-4c37a0f1a267e3d63915133075006902-640-0.jpg')
select * from ARTICULOS